[package]
name = "pstr"
version = "0.1.0"
authors = ["Package <u2a5f@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.4.1"